default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 0.0.0.0
  database: nfl-rushing
  username: nfl-rushing
  password: 'nfl-rushing!23'
  port: 5450

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: nfl_rushing_production
  username: nfl_rushing
  password: <%= ENV['NFL_RUSHING_DATABASE_PASSWORD'] %>
